#
server:
  port: 8999
#
eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}
      management.context-path: /actuator
#
management:
  server:
    port: 7999
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
#
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    clientA:
      path: /a/**
      serviceId: client-a
    clientB:
      path: /b/**
      serviceId: client-b
    clientC:
      path: /c/**
      serviceId: client-c