server:
  port: 8200
management:
  server:
    port: 0 # random port
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'