#
server:
  port: 8761
#
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
  instance:
    metadata-map:
      management.port: ${management.server.port}
      management.context-path: /actuator
#
management:
  server:
    port: 7761
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'