server:
  port: 8761
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8000
        username: username
        password: password
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
management:
  server:
    port: 0 # random port
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'