version: '2.1'

services:
  genv-influxdb:
    image: influxdb:1.7.6
  genv-chronograf:
    image: chronograf:1.7.17
    ports:
      - 8888:8888
  genv-zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  genv-kafka:
    image: confluentinc/cp-kafka:5.3.1
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=genv-kafka
      - KAFKA_ZOOKEEPER_CONNECT=genv-zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INTERNAL://genv-kafka:9091,LISTENER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - genv-zookeeper
  genv-kafdrop:
    image: obsidiandynamics/kafdrop:3.23.0
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: genv-kafka:9091
    depends_on:
      - genv-kafka
  genv-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - discovery.type=single-node
    depends_on:
      - genv-kafka
  genv-kibana:
    image: kibana:7.2.0
    environment:
      ELASTICSEARCH_HOSTS: http://genv-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - genv-elasticsearch
  genv-fluentd:
    build: genv-fluentd/
    volumes:
      - ./genv-fluentd/conf:/fluentd/etc
    depends_on:
      - genv-elasticsearch
  env-eureka:
    build: env-eureka/
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
      - logging.config=classpath:config/logback-spring.xml
      - management.metrics.export.influx.uri=http://genv-influxdb:8086
    depends_on:
      - genv-kafka
      - genv-elasticsearch
      - genv-fluentd
      - genv-kibana
  env-configuration:
    build: env-configuration/
    mem_limit: 512mb
    environment:
      - spring.profiles.active=native
      - logging.config=classpath:config/logback-spring.xml
      - management.metrics.export.influx.uri=http://genv-influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
  env-authorization:
    build: env-authorization/
    restart: always
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
      - logging.config=classpath:config/logback-spring.xml
      - management.metrics.export.influx.uri=http://genv-influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
      - env-configuration
  app-game:
    build: app-game/
    restart: always
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
      - logging.config=classpath:config/logback-spring.xml
      - management.metrics.export.influx.uri=http://genv-influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
      - env-configuration
      - env-authorization
  app-reference:
    build: app-reference/
    restart: always
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
      - logging.config=classpath:config/logback-spring.xml
      - management.metrics.export.influx.uri=http://genv-influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
      - env-configuration
      - env-authorization
  env-zuul:
    build: env-zuul/
    restart: always
    mem_limit: 512mb
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=docker
      - logging.config=classpath:config/logback-spring.xml
      - management.metrics.export.influx.uri=http://genv-influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - app-game
      - app-reference
      - env-eureka
      - env-configuration
      - env-authorization
  env-sba:
    build: env-sba/
    restart: always
    mem_limit: 512mb
    ports:
      - 8081:8081
    environment:
      - spring.profiles.active=docker
      - logging.config=classpath:config/logback-spring.xml
      - management.metrics.export.influx.uri=http://genv-influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - app-game
      - app-reference
      - env-eureka
      - env-authorization
      - env-configuration
      - env-zuul