version: '2.1'

services:
  influxdb:
    image: influxdb:1.7.6
  chronograf:
    image: chronograf:1.7.17
    ports:
      - 8888:8888
  env-eureka:
    image: shermende/spring-cloud/env-eureka
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
  env-configuration:
    image: shermende/spring-cloud/env-configuration
    mem_limit: 512mb
    environment:
      - spring.profiles.active=native
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
  env-authorization:
    image: shermende/spring-cloud/env-authorization
    restart: always
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
      - env-configuration
  app-game:
    image: shermende/spring-cloud/app-game
    restart: always
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
      - management.metrics.export.influx.uri=http://influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
      - env-configuration
      - env-authorization
  app-reference:
    image: shermende/spring-cloud/app-reference
    restart: always
    mem_limit: 512mb
    environment:
      - spring.profiles.active=docker
      - management.metrics.export.influx.uri=http://influxdb:8086
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - env-eureka
      - env-configuration
      - env-authorization
  env-zuul:
    image: shermende/spring-cloud/env-zuul
    restart: always
    mem_limit: 512mb
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=docker
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - app-game
      - app-reference
      - env-eureka
      - env-configuration
      - env-authorization
  env-sba:
    image: shermende/spring-cloud/env-sba
    restart: always
    mem_limit: 512mb
    ports:
      - 8081:8081
    environment:
      - spring.profiles.active=docker
      - eureka.client.serviceUrl.defaultZone=http://env-eureka:8761/eureka/
    depends_on:
      - app-game
      - app-reference
      - env-eureka
      - env-authorization
      - env-configuration
      - env-zuul