#
version: @project.version@
#
server:
  port: 8888
#
spring:
  profiles:
    active: native
  security:
    user:
      name: support
      password: support
  cloud:
    config:
      server:
        native:
          search-locations: classpath:git/
#
management:
  server:
    port: 7888