server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: configuration
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/git
  boot:
    admin:
      client:
        url: sba-url
        username: username
        password: password
        instance:
          metadata:
            user:
              name: username
              password: password
management:
  server:
    port: 0 # random port
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'