#
server:
  port: 8888
#
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/git
#
eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}
      management.context-path: /actuator
#
management:
  server:
    port: 7888
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'