#
server:
  port: 8500
#
spring:
  datasource:
    url: jdbc:h2:mem:game
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
#
eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}
      management.context-path: /actuator
#
management:
  server:
    port: 7500 # random port
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'