#
version: @project.version@
#
server:
  port: 8100
  error:
    include-binding-errors: always
#
spring:
  security:
    user:
      name: support
      password: support
  datasource:
    url: jdbc:h2:mem:reference
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
#
management:
  server:
    port: 7100