#
version: @project.version@
#
server:
  port: 8082
  error:
    include-binding-errors: always
#
spring:
  datasource:
    url: jdbc:h2:mem:auth
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update