#
server:
  port: 8000
#
spring:
  security:
    user:
      name: username
      password: password
#
eureka:
  instance:
    metadata-map:
      user.name: username
      user.password: password
      management.port: ${management.server.port}
      management.context-path: /actuator
#
management:
  server:
    port: 7000
  endpoint:
    health:
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'